### ISSUE TITLE
Redirect component bulk updates - add ability to set status code #12001

### ISSUE THREAD

**Issue by brianteeman** [brianteeman/joomla-cms#12]
I created a branch with the PR (https://github.com/brianteeman/joomla-cms/tree/bul-redirect-status)

I thought it was going to be really simple and all I would have to do would be to create the links.xml for the field which is already defined and used as redirect.php and then inlcude the form in the view wrapped in the check to see if we are in advanced mode but I have obviously missed something. Without the `						<?php echo $this->form->renderFieldset('advanced'); ?>
` the check works so I know thats ok but when I put that line in there I get "Call to a member function renderFieldset() on null"

I am sure it must be something simple I am missing. @zero-24 any ideas/help

**Comment by zero-24** [comment]
hmm dont we want to add this to the batch form? to me it looks like you addid it to the new form?

**Comment by brianteeman** [comment]
batch forms for com_redirect are a actually bulkimport
this is the correct place for batch changes

**Comment by zero-24** [comment]
Ah ok got it now.

It looks like this form does not support form.

if you hit the update button it calls this method: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_redirect/controllers/links.php#L69

and than here: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_redirect/controllers/links.php#L90

this method: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_redirect/models/link.php#L214

so we need to extend the view and than get the values from input in the methods above.

**Comment by brianteeman** [comment]
thinking about it this really should be done as a real batch method. going to delete this branch
