### ISSUE TITLE
hide language options j4

### ISSUE THREAD

**Issue by brianteeman** [brianteeman/joomla-cms#63]
my branch **ismulti2** for j4 is a remake of https://github.com/joomla/joomla-cms/pull/17086 with all the fixes from the comments

got stuck on one part - hiding the language search filter
This code should work https://github.com/brianteeman/joomla-cms/blob/ismulti2/administrator/components/com_content/View/Articles/Html.php#L134 as it works elsewhere but here is produces

```
An error has occurred.
0 Class 'Joomla\Component\Content\Administrator\View\Articles\JLanguageMultilang' not found

```

I assume i am missing something obvious can you point me in the correct direction please @wilsonge @zero-24 and then i can finish this pr

**Comment by wilsonge** [comment]
Change line 135 to `\JLanguageMultilang`

**Comment by brianteeman** [comment]
Thanks

**Comment by zero-24** [comment]
Sorry i have not noticed that :( But looks like George was faster :)
